name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  typo-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for typos
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "docs/**/*.{md,mdx}"
